- 异常情形是指组织当前方法或作用域继续执行的问题，与普通问题有所区分 p249

  普通问题是指：在当前环境下能够得到足够的信息，总能处理这个错误

  异常情形是指：在当前环境下无法获得必要的信息来解决问题，此时**唯一能做的就是从当前环境跳出，并且把问题交给上一级的环境**

- 抛出异常后发生的几件事情： p249

  1. 首先会使用new在堆上创建异常对象
  2. 从当前执行路径被终止，并且从当前环境中弹出堆异常对象的引用
  3. 异常处理机制接管程序，并开始寻找一个恰当的地方来继续执行程序，这个恰当的地方被称为**异常处理程序**

- 异常参数 p250

  所有的标准异常类都有两个构造器：

  1. 一个是默认构造器
  2. 一个是接收字符串作为参数，以便能把相关信息放入异常对象的构造器

- 监控区域 p250

  即`try`、`catch`

  ```java
  try {
      
  } catch(Type t1) {
      
  } catch(Type t2) {
      
  }
  ```

  当异常被抛出的时候，异常处理机制将负责搜寻参数与异常类型相匹配的**第一个程序**

- 终止与恢复 p251

  异常处理理论上有两种基本模型：

  1. 终止类型
  2. 恢复类型

- 创建自定义的异常 p251

  要定义异常类，**必须从已有的异常类继承**

  ```java
  class SimpleException extends Exception {}
  
  public class InheritingExceptions {
    public void f() throws SimpleException {
      System.out.println("Throw SimpleException from f()");
      throw new SimpleException();
    }
    public static void main(String[] args) {
      InheritingExceptions sed = new InheritingExceptions();
      try {
        sed.f();
      } catch(SimpleException e) {
        System.out.println("Caught it!");
      }
    }
  } /* Output:
  Throw SimpleException from f()
  Caught it!
  *///:~
  ```

  编译器创建了默认构造器，它将自动调用基类的默认构造器

- 异常说明 p256

  异常说明使用了附加的关键字`throws`，后面接一个所有潜在异常类型的列表，如下所示：

  ```java
  void f() throws TooBig, TooSmall, DivZero
  ```

  **代码必须与异常说明保持一致**，如果方法里的代码产生了异常却没有进行处理，编译器会进行提醒：要么处理这个异常，要么就在一场说明中表明此方法将产生异常。

  不过有一种特殊情况，可以声明方法将要抛出异常，而实际上却不抛出，这样可以为异常先站一个位子，之后就可以抛出这种异常而不需要修改已有的代码

- 捕获所有的异常 p256

  ```java
  catch(Exception e) {
      ...
  }
  ```

  一般将上述代码放在程序列表的末尾，以防抢在其他处理程序之前先行捕获异常

- 一些异常处理的方法 p256

  因为**Exception**是与变成有关的所有异常类的基类，所以它不会有太具体的信息，不过可以调用它从其基类**Throwable**继承的方法(能够抛出任意类型的**Throwable**对象，它是异常类型的根类 p250)

  1. `String getMessage()`
  2. `String getLocalizedMessage()`

  上述两种方法用来获取详细信息，或者本地语言表示的详细信息

  1. `String toString()`

  上述方法返回对**Throwable**的简单描述，要是有详细描述的话，也会把它包括在内

  1. `void printStackTrace()`
  2. `void printStackTrace(PrintStream)`
  3. `void printStackTrace(java.io.PrintWriter)`

  上述方法打印**Throwable**和**Throwable**的调用栈轨迹

  1. `Throwable fillInStackTrace()`

  上述方法用于在**Throwable**对象的内部记录栈帧的当前状态

  除上述方法以外，也可以使用**Throwable**从其基类**Object**继承的方法

  ```java
  public class ExceptionMethods {
    public static void main(String[] args) {
      try {
        throw new Exception("My Exception");
      } catch(Exception e) {
        print("Caught Exception");
        print("getMessage():" + e.getMessage());
        print("getLocalizedMessage():" +
          e.getLocalizedMessage());
        print("toString():" + e);
        print("printStackTrace():");
        e.printStackTrace(System.out);
      }
    }
  } /* Output:
  Caught Exception
  getMessage():My Exception
  getLocalizedMessage():My Exception
  toString():java.lang.Exception: My Exception
  printStackTrace():
  java.lang.Exception: My Exception
          at ExceptionMethods.main(ExceptionMethods.java:8)
  *///:~
  ```

  观察上述代码，可以发现每个方法都比前一个提供了更多的信息----实际上它们每一个都是前一个的超集

- 栈轨迹 p257

  `printStackTrace()`可以打印出调用栈轨迹，其提供的信息可以通过`getStackTrack()`来直接访问，`getStackTrack()`方法返回一个由栈轨迹中的元素组成的数组，其中每一个元素都表示栈中的一帧

  ```java
  public class WhoCalled {
    static void f() {
      // Generate an exception to fill in the stack trace
      try {
        throw new Exception();
      } catch (Exception e) {
        for(StackTraceElement ste : e.getStackTrace()) //使用e.getStackTrace()
          System.out.println(ste.getMethodName());
      }
    }
    static void g() { f(); }
    static void h() { g(); }
    public static void main(String[] args) {
      f();
      System.out.println("--------------------------------");
      g();
      System.out.println("--------------------------------");
      h();
    }
  } /* Output:
  f
  main
  --------------------------------
  f
  g
  main
  --------------------------------
  f
  g
  h
  main
  *///:~
  ```

- 重新抛出异常 p258

  有时希望把刚捕获的异常重新抛出，尤其是在使用**Exception**捕获异常的时候

  ```java
  catch(Exception e) {
      balabala;
      throw e;
  }
  ```

  重抛异常会把异常抛给**上一级环境**中的异常处理程序，**同一个try块的后续catch子句将被忽略**，此外，异常对象的所有信息都得以保持，所以高一级的环境中捕获此异常的处理程序可以从这个异常对象中得到所有信息

  **注意：**如果只是将异常对象重新抛出，使用`printStackTrace()`方法显示的将是**原来异常抛出点**的调用栈信息，此时可以调用`fillInStackTrace()`方法，这将返回一个**Throwable**对象

  ```java
  public class Rethrowing {
    public static void f() throws Exception {
      System.out.println("originating the exception in f()");
      throw new Exception("thrown from f()");
    }
    public static void g() throws Exception {
      try {
        f();
      } catch(Exception e) {
        System.out.println("Inside g(),e.printStackTrace()");
        e.printStackTrace(System.out);
        throw e;
      }
    }
    public static void h() throws Exception {
      try {
        f();
      } catch(Exception e) {
        System.out.println("Inside h(),e.printStackTrace()");
        e.printStackTrace(System.out);
        throw (Exception)e.fillInStackTrace(); //这个方法会返回一个Throwable对象
      }
    }
    public static void main(String[] args) {
      try {
        g();
      } catch(Exception e) {
        System.out.println("main: printStackTrace()");
        e.printStackTrace(System.out);
      }
      try {
        h();
      } catch(Exception e) {
        System.out.println("main: printStackTrace()");
        e.printStackTrace(System.out);
      }
    }
  } /* Output:
  originating the exception in f()
  Inside g(),e.printStackTrace()
  java.lang.Exception: thrown from f()
          at Rethrowing.f(Rethrowing.java:7)
          at Rethrowing.g(Rethrowing.java:11)
          at Rethrowing.main(Rethrowing.java:29)
  main: printStackTrace()
  java.lang.Exception: thrown from f()
          at Rethrowing.f(Rethrowing.java:7)
          at Rethrowing.g(Rethrowing.java:11)
          at Rethrowing.main(Rethrowing.java:29)
  originating the exception in f()
  Inside h(),e.printStackTrace()
  java.lang.Exception: thrown from f()
          at Rethrowing.f(Rethrowing.java:7)
          at Rethrowing.h(Rethrowing.java:20)
          at Rethrowing.main(Rethrowing.java:35)
  main: printStackTrace()
  java.lang.Exception: thrown from f() 这里就和上面不一样了
          at Rethrowing.h(Rethrowing.java:24)
          at Rethrowing.main(Rethrowing.java:35) 
  *///:~
  ```

  有可能在捕获异常之后抛出另一种异常，这样做的话，得到的效果类似于使用`fillInStackTrace()`，有关原来异常发生点的信息就会对视，剩下的只有新的信息

- 永远不必为异常对象担心，因为异常对象都是new出来的，垃圾回收期会自动把它们清理掉 p260

- 异常链 p260

  有时希望捕获一个异常之后抛出另一个异常，并且不希望丢掉原来的异常信息，在JDK1.4之后，所有的**Throwable**的子类在构造器中都可以接受一个*cause*对象作为参数，*cause*这个参数用来表示原始异常

  **注意：**在**Throwable**的子类中，只有3种基本的异常类提供了带*cause*参数的构造器，分别是**Error**、**Exception**以及**RuntimeException**

  如果想要把其他类型的异常链接起来，应该使用`initCause()`方法而不是构造器

  ```java
  class DynamicFieldsException extends Exception {}
  
  public class DynamicFields {
    private Object[][] fields;
    public DynamicFields(int initialSize) {
      fields = new Object[initialSize][2];
      for(int i = 0; i < initialSize; i++)
        fields[i] = new Object[] { null, null };
    }
    public String toString() {
      StringBuilder result = new StringBuilder();
      for(Object[] obj : fields) {
        result.append(obj[0]);
        result.append(": ");
        result.append(obj[1]);
        result.append("\n");
      }
      return result.toString();
    }
    private int hasField(String id) {
      for(int i = 0; i < fields.length; i++)
        if(id.equals(fields[i][0]))
          return i;
      return -1;
    }
    private int
    getFieldNumber(String id) throws NoSuchFieldException {
      int fieldNum = hasField(id);
      if(fieldNum == -1)
        throw new NoSuchFieldException();
      return fieldNum;
    }
    private int makeField(String id) {
      for(int i = 0; i < fields.length; i++)
        if(fields[i][0] == null) {
          fields[i][0] = id;
          return i;
        }
      // No empty fields. Add one:
      Object[][] tmp = new Object[fields.length + 1][2];
      for(int i = 0; i < fields.length; i++)
        tmp[i] = fields[i];
      for(int i = fields.length; i < tmp.length; i++)
        tmp[i] = new Object[] { null, null };
      fields = tmp;
      // Recursive call with expanded fields:
      return makeField(id);
    }
    public Object
    getField(String id) throws NoSuchFieldException {
      return fields[getFieldNumber(id)][1];
    }
    public Object setField(String id, Object value)
    throws DynamicFieldsException {
      if(value == null) {
        // Most exceptions don't have a "cause" constructor.
        // In these cases you must use initCause(),
        // available in all Throwable subclasses.
        DynamicFieldsException dfe =
          new DynamicFieldsException();
        dfe.initCause(new NullPointerException()); //这里采用了initCause方法
        throw dfe;
      }
      int fieldNumber = hasField(id);
      if(fieldNumber == -1)
        fieldNumber = makeField(id);
      Object result = null;
      try {
        result = getField(id); // Get old value
      } catch(NoSuchFieldException e) {
        // Use constructor that takes "cause":
        throw new RuntimeException(e); //这里使用了构造器
      }
      fields[fieldNumber][1] = value;
      return result;
    }
    public static void main(String[] args) {
      DynamicFields df = new DynamicFields(3);
      print(df);
      try {
        df.setField("d", "A value for d");
        df.setField("number", 47);
        df.setField("number2", 48);
        print(df);
        df.setField("d", "A new value for d");
        df.setField("number3", 11);
        print("df: " + df);
        print("df.getField(\"d\") : " + df.getField("d"));
        Object field = df.setField("d", null); // Exception
      } catch(NoSuchFieldException e) {
        e.printStackTrace(System.out);
      } catch(DynamicFieldsException e) {
        e.printStackTrace(System.out);
      }
    }
  } /* Output:
  null: null
  null: null
  null: null
  
  d: A value for d
  number: 47
  number2: 48
  
  df: d: A new value for d
  number: 47
  number2: 48
  number3: 11
  
  df.getField("d") : A new value for d
  DynamicFieldsException
          at DynamicFields.setField(DynamicFields.java:64)
          at DynamicFields.main(DynamicFields.java:94)
  Caused by: java.lang.NullPointerException
          at DynamicFields.setField(DynamicFields.java:66)
          ... 1 more
  *///:~
  ```