- java标准异常 p263

  Throwable这个java类可以用来表示任何可以作为异常被抛出的类，Throwable对象可分为两种类型：

  1. Error用来表示编译时和系统错误
  2. Exception是可以被抛出的基本类型

- 特例: RuntimeException p263

  ```java
  if(t == null)
      throw new NullPointerException;
  ```

  上述代码其实是多余的，java会自动来做，它属于java标准运行时检测的一部分，属于运行时异常的类型有很多，它们会自动被java虚拟机抛出，所以不必在异常说明中把它们列出来，这些异常都是从**RuntimeException**类继承而来，这些异常称为"不受检查异常"

  如果**RuntimeException**没有被捕获而直达`main()`，那么在程序推出前将调用异常的`printStackTrace()`方法

- 使用finally进行清理 p264

- 遗憾：异常缺失 p268

  ```java
  class VeryImportantException extends Exception {
    public String toString() {
      return "A very important exception!";
    }
  }
  
  class HoHumException extends Exception {
    public String toString() {
      return "A trivial exception";
    }
  }
  
  public class LostMessage {
    void f() throws VeryImportantException {
      throw new VeryImportantException();
    }
    void dispose() throws HoHumException {
      throw new HoHumException();
    }
    public static void main(String[] args) {
      try {
        LostMessage lm = new LostMessage();
        try {
          lm.f();
        } finally {
          lm.dispose();
        }
      } catch(Exception e) {
        System.out.println(e);
      }
    }
  } /* Output:
  A trivial exception
  *///:~
  ```

  从输出中可以看到，**VeryImportantExcception**不见了，它被finally子句中的**HohumException**所取代，相比之下，在C++中将"前一个异常还没处理就抛出下一个异常的这种情况看成是一种糟糕的编程错误"

  除上述方法以外，还有一种情况会丢失异常，就是从finally子句中返回：

  ```java
  public class ExceptionSilencer {
    public static void main(String[] args) {
      try {
        throw new RuntimeException();
      } finally {
        // Using 'return' inside the finally block
        // will silence any thrown exception.
        return;
      }
    }
  } ///:~
  ```

- 异常的限制 p269

  ```java
  class BaseballException extends Exception {}
  class Foul extends BaseballException {}
  class Strike extends BaseballException {}
  
  abstract class Inning {
    public Inning() throws BaseballException {}
    public void event() throws BaseballException {
      // Doesn't actually have to throw anything
    }
    public abstract void atBat() throws Strike, Foul;
    public void walk() {} // Throws no checked exceptions
  }
  
  class StormException extends Exception {}
  class RainedOut extends StormException {}
  class PopFoul extends Foul {}
  
  interface Storm {
    public void event() throws RainedOut;
    public void rainHard() throws RainedOut;
  }
  
  public class StormyInning extends Inning implements Storm {
    // OK to add new exceptions for constructors, but you
    // must deal with the base constructor exceptions:
    public StormyInning()
      throws RainedOut, BaseballException {} //RainedOut这里是随便声明的，没有也可以，但BaseballException是必须要声明的,这是因为异常限制对构造器不起作用，而基类构造器必须以这样或那样的方式被调用，因此派生类构造器的异常说明必须包含基类构造器的异常说明
    public StormyInning(String s)
      throws Foul, BaseballException {}
    // Regular methods must conform to base class:
    public void walk() throws PopFoul {} //Compile error 编译错误，这是因为在基类中这个方法不会抛出异常的，加入子类抛出异常那么编译器在编译阶段是没办法判断出哪个方法会抛出异常(因为只有运行的时候才会知道自己要调用子类对象还是基类对象)
    // Interface CANNOT add exceptions to existing
    // methods from the base class:
    //public void event() throws RainedOut {} //这里也不OK，和上面问题相同
    // If the method doesn't already exist in the
    // base class, the exception is OK:
    public void rainHard() throws RainedOut {}
    // You can choose to not throw any exceptions,
    // even if the base version does:
    public void event() {} //可以不throw
    // Overridden methods can throw inherited exceptions:
    public void atBat() throws PopFoul {} //可以抛出子类，因为atBat()在Inning中throw Foul，而Foul是PopFoul的父类，PopFoul可以被捕获到
    public static void main(String[] args) {
      try {
        StormyInning si = new StormyInning();
        si.atBat();
      } catch(PopFoul e) {
        System.out.println("Pop foul");
      } catch(RainedOut e) {
        System.out.println("Rained out");
      } catch(BaseballException e) {
        System.out.println("Generic baseball exception");
      }
      // Strike not thrown in derived version.
      try {
        // What happens if you upcast?
        Inning i = new StormyInning(); //向上转型之后，必须要catch到基类中throw的exceptions
        i.atBat();
        // You must catch the exceptions from the
        // base-class version of the method:
      } catch(Strike e) {
        System.out.println("Strike");
      } catch(Foul e) {
        System.out.println("Foul");
      } catch(RainedOut e) {
        System.out.println("Rained out");
      } catch(BaseballException e) {
        System.out.println("Generic baseball exception");
      }
    }
  }
  ```

  尽管在继承过程中，编译器会对异常说明做强制要求，但异常说明本身并不属于方法类型的一部分，方法类型是由**方法的名字与参数的类型组成的**，因此，不能基于异常说明来重载方法，此外，一个出现在基类方法的异常说明中的异常，不一定会出现在派生类方法的异常说明里，这点同继承的规则明显不同

- 构造器 p274

  ```java
  class NeedsCleanup { // Construction can't fail
    private static long counter = 1;
    private final long id = counter++;
    public void dispose() {
      System.out.println("NeedsCleanup " + id + " disposed");
    }
  }
  
  class ConstructionException extends Exception {}
  
  class NeedsCleanup2 extends NeedsCleanup {
    // Construction can fail:
    public NeedsCleanup2() throws ConstructionException {}
  }
  
  public class CleanupIdiom {
    public static void main(String[] args) {
      // Section 1:
      NeedsCleanup nc1 = new NeedsCleanup();
      try {
        // ...
      } finally {
        nc1.dispose();
      }
  
      // Section 2:
      // If construction cannot fail you can group objects:
      NeedsCleanup nc2 = new NeedsCleanup();
      NeedsCleanup nc3 = new NeedsCleanup();
      try {
        // ...
      } finally {
        nc3.dispose(); // Reverse order of construction
        nc2.dispose();
      }
  
      // Section 3:
      // If construction can fail you must guard each one:
      try {
        NeedsCleanup2 nc4 = new NeedsCleanup2();
        try {
          NeedsCleanup2 nc5 = new NeedsCleanup2();
          try {
            // ...
          } finally {
            nc5.dispose();
          }
        } catch(ConstructionException e) { // nc5 constructor
          System.out.println(e);
        } finally {
          nc4.dispose();
        }
      } catch(ConstructionException e) { // nc4 constructor
        System.out.println(e);
      }
    }
  } /* Output:
  NeedsCleanup 1 disposed
  NeedsCleanup 3 disposed
  NeedsCleanup 2 disposed
  NeedsCleanup 5 disposed
  NeedsCleanup 4 disposed
  *///:~
  ```

  在main()中，Section 1相当简单，遵循了在可去除对象之后紧跟try-finally的原则，如果对象构造不能失败，就不需要catch

  在Section 2中，为了构造和清理，可以看到具有不能失败的构造器可以群组在一起

  Section 3展示了如何处理那些具有可以失败的构造器，较为复杂

